---
#
# Ansible managed
#
repository:
  description: Install and configure [Bareos](https://www.bareos.com/) Storage Daemon.
  homepage: https://adfinis.com/
  topics: bareos, infrastructure, linux, storage, system, tools, ansible, molecule, tox, playbook
