---
# tasks file for bareos_sd

- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
    - main.yml  # fallback

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install packages
  ansible.builtin.package:
    name: "{{ bareos_sd_packages }}"

- name: Install debug packages
  ansible.builtin.package:
    name: "{{ bareos_sd_debug_packages }}"
  when:
    - bareos_sd_install_debug_packages

- name: Place bareos-sd.conf
  ansible.builtin.template:
    src: bareos-sd.conf.j2
    dest: "/etc/bareos/bareos-sd.d/storage/bareos-sd.conf"
    owner: bareos
    group: bareos
    mode: "0640"
    backup: "{{ bareos_sd_backup_configurations }}"
  notify:
    - Check configuration
    - Restart bareos-sd

- name: Place device
  ansible.builtin.template:
    src: device.conf.j2
    dest: "/etc/bareos/bareos-sd.d/device/{{ item.name }}.conf"
    owner: bareos
    group: bareos
    mode: "0640"
    backup: "{{ bareos_sd_backup_configurations }}"
  loop: "{{ bareos_sd_devices }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Check configuration
    - Restart bareos-sd

- name: Place director
  ansible.builtin.template:
    src: director.conf.j2
    dest: "/etc/bareos/bareos-sd.d/director/{{ item.name }}.conf"
    owner: bareos
    group: bareos
    mode: "0640"
    backup: "{{ bareos_sd_backup_configurations }}"
  loop: "{{ bareos_sd_directors }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Check configuration
    - Restart bareos-sd

- name: Place message
  ansible.builtin.template:
    src: message.conf.j2
    dest: "/etc/bareos/bareos-sd.d/messages/{{ item.name }}.conf"
    owner: bareos
    group: bareos
    mode: "0640"
    backup: "{{ bareos_sd_backup_configurations }}"
  loop: "{{ bareos_sd_messages }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Check configuration
    - Restart bareos-sd

- name: Install bareos-storage-droplet
  ansible.builtin.package:
    name: bareos-storage-droplet
  when:
    - bareos_sd_s3_profiles | length > 0

- name: Create /etc/bareos/bareos-sd.d/device/droplet
  ansible.builtin.file:
    path: /etc/bareos/bareos-sd.d/device/droplet
    state: directory
    owner: bareos
    group: bareos
    mode: "0755"
  when:
    - bareos_sd_s3_profiles | length > 0

- name: Place S3 profile
  ansible.builtin.template:
    src: s3.profile.j2
    dest: /etc/bareos/bareos-sd.d/device/droplet/{{ item.name }}.profile
    owner: bareos
    group: bareos
    mode: "0600"
  loop: "{{ bareos_sd_s3_profiles }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_s3_profiles | length > 0
  notify:
    - Check configuration
    - Restart bareos-sd

- name: Place Autochanger
  ansible.builtin.template:
    src: autochanger.conf.j2
    dest: /etc/bareos/bareos-sd.d/autochanger/{{ item.name }}.conf
    owner: bareos
    group: bareos
    mode: "0600"
    backup: "{{ bareos_sd_backup_configurations }}"
  loop: "{{ bareos_sd_autochangers }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_autochangers is iterable
    - bareos_sd_autochangers | length > 0
    - item.name is defined
    - item.changer_device is defined
    - item.devices is defined
    - item.devices | length > 0
  notify:
    - Check configuration
    - Restart bareos-sd


- name: Start and enable bareos-sd service
  ansible.builtin.service:
    name: bareos-sd
    state: started
    enabled: true
